export enum ERROR_TYPE {
    NAME_NOT_FOUND="NAME_NOT_FOUND",
    USER_NOT_FOUND="USER_NOT_FOUND",
    YOU_DO_NOT_HAVE_ENOUGH_COIN="YOU_DO_NOT_HAVE_ENOUGH_COIN",
    POST_NOT_FOUND="POST_NOT_FOUND",
    CAN_NOT_FOLLOW_YOUR_SELF="CAN_NOT_FOLLOW_YOUR_SELF"
}